from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
import os


class RegimeUncertainBehavior(str, Enum):
    DEGRADE = "degrade"
    RESTRICT = "restrict"
    BLOCK = "block"


def _b(name: str, default: bool) -> bool:
    return str(os.environ.get(name, str(default))).lower() in {"1", "true", "yes", "on"}


def _f(name: str, default: float) -> float:
    return float(os.environ.get(name, str(default)))


def _i(name: str, default: int) -> int:
    return int(os.environ.get(name, str(default)))


@dataclass(frozen=True)
class ControlPlaneConfig:
    CONTROL_PLANE_ENABLED: bool = _b("CONTROL_PLANE_ENABLED", True)
    CONTROL_PLANE_STRICT_MODE: bool = _b("CONTROL_PLANE_STRICT_MODE", False)
    REGIME_ENGINE_ENABLED: bool = _b("REGIME_ENGINE_ENABLED", True)
    REGIME_LOOKBACK_BARS_M5: int = _i("REGIME_LOOKBACK_BARS_M5", 120)
    REGIME_LOOKBACK_BARS_M15: int = _i("REGIME_LOOKBACK_BARS_M15", 96)
    REGIME_LOOKBACK_BARS_H1: int = _i("REGIME_LOOKBACK_BARS_H1", 96)
    REGIME_MIN_CONFIDENCE: float = _f("REGIME_MIN_CONFIDENCE", 0.55)
    REGIME_UNCERTAIN_BEHAVIOR: RegimeUncertainBehavior = RegimeUncertainBehavior(os.environ.get("REGIME_UNCERTAIN_BEHAVIOR", "restrict"))
    TREND_STRENGTH_THRESHOLD: float = _f("TREND_STRENGTH_THRESHOLD", 0.62)
    ROTATION_THRESHOLD: float = _f("ROTATION_THRESHOLD", 0.58)
    COMPRESSION_THRESHOLD: float = _f("COMPRESSION_THRESHOLD", 0.60)
    EXPANSION_THRESHOLD: float = _f("EXPANSION_THRESHOLD", 0.60)
    DEAD_ZONE_THRESHOLD: float = _f("DEAD_ZONE_THRESHOLD", 0.65)
    EVENT_CHAOS_THRESHOLD: float = _f("EVENT_CHAOS_THRESHOLD", 0.70)
    PORTFOLIO_ALLOCATOR_ENABLED: bool = _b("PORTFOLIO_ALLOCATOR_ENABLED", True)
    ALLOC_MAX_NEW_TRADES_PER_CYCLE: int = _i("ALLOC_MAX_NEW_TRADES_PER_CYCLE", 3)
    ALLOC_MAX_USD_NET_EXPOSURE: float = _f("ALLOC_MAX_USD_NET_EXPOSURE", 0.04)
    ALLOC_MAX_SINGLE_MACRO_CLUSTER_RISK: float = _f("ALLOC_MAX_SINGLE_MACRO_CLUSTER_RISK", 0.02)
    ALLOC_MAX_CORRELATED_BUCKET_RISK: float = _f("ALLOC_MAX_CORRELATED_BUCKET_RISK", 0.02)
    ALLOC_MAX_INSTRUMENT_DUPLICATION: int = _i("ALLOC_MAX_INSTRUMENT_DUPLICATION", 1)
    ALLOC_MIN_PRIORITY_SCORE: float = _f("ALLOC_MIN_PRIORITY_SCORE", 0.20)
    ALLOC_ENABLE_RESIZING: bool = _b("ALLOC_ENABLE_RESIZING", True)
    ALLOC_ENABLE_BLOCKING: bool = _b("ALLOC_ENABLE_BLOCKING", True)
    ALLOC_PRIORITY_EV_WEIGHT: float = _f("ALLOC_PRIORITY_EV_WEIGHT", 0.35)
    ALLOC_PRIORITY_EXEC_WEIGHT: float = _f("ALLOC_PRIORITY_EXEC_WEIGHT", 0.20)
    ALLOC_PRIORITY_EDGE_WEIGHT: float = _f("ALLOC_PRIORITY_EDGE_WEIGHT", 0.15)
    ALLOC_PRIORITY_REGIME_WEIGHT: float = _f("ALLOC_PRIORITY_REGIME_WEIGHT", 0.15)
    ALLOC_PRIORITY_EVENT_WEIGHT: float = _f("ALLOC_PRIORITY_EVENT_WEIGHT", 0.10)
    CORRELATION_LOOKBACK_DAYS: int = _i("CORRELATION_LOOKBACK_DAYS", 30)
    CORRELATION_MIN_ABS_FOR_CLUSTER: float = _f("CORRELATION_MIN_ABS_FOR_CLUSTER", 0.65)
    CORRELATION_REFRESH_MINUTES: int = _i("CORRELATION_REFRESH_MINUTES", 60)
    EVENT_ENGINE_ENABLED: bool = _b("EVENT_ENGINE_ENABLED", True)
    EVENT_CALENDAR_ENABLED: bool = _b("EVENT_CALENDAR_ENABLED", True)
    EVENT_PRE_LOCKOUT_MINUTES: int = _i("EVENT_PRE_LOCKOUT_MINUTES", 30)
    EVENT_POST_DIGESTION_MINUTES: int = _i("EVENT_POST_DIGESTION_MINUTES", 45)
    EVENT_SPREAD_NORMALIZATION_WINDOW_MINUTES: int = _i("EVENT_SPREAD_NORMALIZATION_WINDOW_MINUTES", 20)
    EVENT_ALLOW_BREAKOUT_POST_RELEASE_ONLY: bool = _b("EVENT_ALLOW_BREAKOUT_POST_RELEASE_ONLY", True)
    EVENT_BLOCK_MEAN_REVERSION_NEAR_HIGH_IMPACT: bool = _b("EVENT_BLOCK_MEAN_REVERSION_NEAR_HIGH_IMPACT", True)
    EVENT_BLOCK_NEW_POSITIONS_IF_CALENDAR_UNAVAILABLE: bool = _b("EVENT_BLOCK_NEW_POSITIONS_IF_CALENDAR_UNAVAILABLE", False)
    EXECUTION_INTEL_ENABLED: bool = _b("EXECUTION_INTEL_ENABLED", True)
    EXECUTION_FILL_PROB_THRESHOLD: float = _f("EXECUTION_FILL_PROB_THRESHOLD", 0.35)
    EXECUTION_MAX_EXPECTED_SLIPPAGE_BPS: float = _f("EXECUTION_MAX_EXPECTED_SLIPPAGE_BPS", 3.0)
    EXECUTION_MAX_LATE_ENTRY_RISK: float = _f("EXECUTION_MAX_LATE_ENTRY_RISK", 0.75)
    EXECUTION_MAX_ESCAPE_RISK: float = _f("EXECUTION_MAX_ESCAPE_RISK", 0.85)
    EXECUTION_REPRICE_ENABLED: bool = _b("EXECUTION_REPRICE_ENABLED", True)
    EXECUTION_DEFAULT_MAX_RETRIES: int = _i("EXECUTION_DEFAULT_MAX_RETRIES", 2)
    EXECUTION_DEFAULT_CANCEL_AFTER_SECONDS: int = _i("EXECUTION_DEFAULT_CANCEL_AFTER_SECONDS", 90)
    ORDER_TACTICS_ENABLED: bool = _b("ORDER_TACTICS_ENABLED", True)
    TACTIC_USE_PASSIVE_LIMIT_FOR_ROTATION: bool = _b("TACTIC_USE_PASSIVE_LIMIT_FOR_ROTATION", True)
    TACTIC_USE_AGGRESSIVE_STOP_FOR_EXPANSION: bool = _b("TACTIC_USE_AGGRESSIVE_STOP_FOR_EXPANSION", True)
    TACTIC_ALLOW_STAGING: bool = _b("TACTIC_ALLOW_STAGING", True)
    TACTIC_MAX_CLIPS: int = _i("TACTIC_MAX_CLIPS", 3)
    TACTIC_MIN_CLIP_SECONDS: int = _i("TACTIC_MIN_CLIP_SECONDS", 4)
    TACTIC_FALLBACK_TO_MARKET_ALLOWED: bool = _b("TACTIC_FALLBACK_TO_MARKET_ALLOWED", True)

    def validate(self) -> None:
        if not (0.0 <= self.REGIME_MIN_CONFIDENCE <= 1.0):
            raise ValueError("REGIME_MIN_CONFIDENCE must be [0,1]")
        if self.ALLOC_MAX_NEW_TRADES_PER_CYCLE < 1:
            raise ValueError("ALLOC_MAX_NEW_TRADES_PER_CYCLE must be >=1")
        if self.TACTIC_MAX_CLIPS < 1:
            raise ValueError("TACTIC_MAX_CLIPS must be >=1")


def load_config() -> ControlPlaneConfig:
    cfg = ControlPlaneConfig()
    cfg.validate()
    return cfg
