"""Centralized reason code constants for control-plane decisions."""

# Regime codes
REGIME_TREND_EXPANSION = "REGIME_TREND_EXPANSION"
REGIME_ROTATION = "REGIME_ROTATION"
REGIME_COMPRESSION = "REGIME_COMPRESSION"
REGIME_SWEEP_REVERSAL = "REGIME_SWEEP_REVERSAL"
REGIME_EVENT_CHAOS = "REGIME_EVENT_CHAOS"
REGIME_DEAD_ZONE = "REGIME_DEAD_ZONE"
REGIME_UNCERTAIN = "REGIME_UNCERTAIN"
REGIME_BREAKOUT_ALLOWED = "REGIME_BREAKOUT_ALLOWED"
REGIME_BREAKOUT_SUPPRESSED = "REGIME_BREAKOUT_SUPPRESSED"
REGIME_MEAN_REVERSION_ALLOWED = "REGIME_MEAN_REVERSION_ALLOWED"
REGIME_MEAN_REVERSION_BLOCKED = "REGIME_MEAN_REVERSION_BLOCKED"
REGIME_PULLBACK_ALLOWED = "REGIME_PULLBACK_ALLOWED"
REGIME_PULLBACK_SUPPRESSED = "REGIME_PULLBACK_SUPPRESSED"

# Allocation codes
ALLOC_CORRELATION_CAP = "ALLOC_CORRELATION_CAP"
ALLOC_USD_CONCENTRATION_CAP = "ALLOC_USD_CONCENTRATION_CAP"
ALLOC_MACRO_DUPLICATION = "ALLOC_MACRO_DUPLICATION"
ALLOC_PORTFOLIO_HEAT_CAP = "ALLOC_PORTFOLIO_HEAT_CAP"
ALLOC_RISK_BUDGET_EXHAUSTED = "ALLOC_RISK_BUDGET_EXHAUSTED"
ALLOC_LOW_PRIORITY = "ALLOC_LOW_PRIORITY"
ALLOC_HIGH_PRIORITY = "ALLOC_HIGH_PRIORITY"
ALLOC_RESIZED_FOR_CLUSTER = "ALLOC_RESIZED_FOR_CLUSTER"
ALLOC_RESIZED_FOR_CONCENTRATION = "ALLOC_RESIZED_FOR_CONCENTRATION"
ALLOC_BLOCKED_BY_PORTFOLIO_FIT = "ALLOC_BLOCKED_BY_PORTFOLIO_FIT"

# Event codes
EVENT_PRE_LOCKOUT = "EVENT_PRE_LOCKOUT"
EVENT_POST_DIGESTION = "EVENT_POST_DIGESTION"
EVENT_SPREAD_NOT_NORMALIZED = "EVENT_SPREAD_NOT_NORMALIZED"
EVENT_BREAKOUT_ONLY = "EVENT_BREAKOUT_ONLY"
EVENT_REVERSION_BLOCKED = "EVENT_REVERSION_BLOCKED"
EVENT_POWELL_HEADLINE_RISK = "EVENT_POWELL_HEADLINE_RISK"
EVENT_HIGH_IMPACT_ACTIVE = "EVENT_HIGH_IMPACT_ACTIVE"
EVENT_RECENT_HIGH_IMPACT = "EVENT_RECENT_HIGH_IMPACT"
EVENT_CALENDAR_UNAVAILABLE = "EVENT_CALENDAR_UNAVAILABLE"
EVENT_NORMAL = "EVENT_NORMAL"

# Execution codes
EXEC_TACTIC_MARKET = "EXEC_TACTIC_MARKET"
EXEC_TACTIC_LIMIT = "EXEC_TACTIC_LIMIT"
EXEC_TACTIC_STOP = "EXEC_TACTIC_STOP"
EXEC_TACTIC_PASSIVE_LIMIT = "EXEC_TACTIC_PASSIVE_LIMIT"
EXEC_TACTIC_AGGRESSIVE_STOP = "EXEC_TACTIC_AGGRESSIVE_STOP"
EXEC_TACTIC_BLOCK_LATE_ENTRY = "EXEC_TACTIC_BLOCK_LATE_ENTRY"
EXEC_TACTIC_BLOCK_SPREAD_DISLOCATION = "EXEC_TACTIC_BLOCK_SPREAD_DISLOCATION"
EXEC_TACTIC_FILL_PROB_LOW = "EXEC_TACTIC_FILL_PROB_LOW"
EXEC_TACTIC_SLIPPAGE_HIGH = "EXEC_TACTIC_SLIPPAGE_HIGH"
EXEC_TACTIC_ESCAPE_RISK_HIGH = "EXEC_TACTIC_ESCAPE_RISK_HIGH"
EXEC_TACTIC_REPRICE_ENABLED = "EXEC_TACTIC_REPRICE_ENABLED"
EXEC_TACTIC_RETRY_ENABLED = "EXEC_TACTIC_RETRY_ENABLED"

# Confluence codes
CONFLUENCE_OK = "CONFLUENCE_OK"
CONFLUENCE_TOO_LOW = "CONFLUENCE_TOO_LOW"

# Surveillance codes
SURVEILLANCE_OK = "SURVEILLANCE_OK"
SURVEILLANCE_SOFT_THROTTLE = "SURVEILLANCE_SOFT_THROTTLE"
SURVEILLANCE_BLOCK_TOXIC_FLOW = "SURVEILLANCE_BLOCK_TOXIC_FLOW"
