REGIME_POLICY_TABLE = {
    "trend_expansion": {
        "allowed": ["Breakout-Squeeze", "Trend-Pullback"],
        "suppressed": ["Range-MeanReversion"],
        "blocked": [],
        "suppression_multipliers": {"Range-MeanReversion": 0.6, "Liquidity-Draw/Sweep": 0.9},
        "ranking_adjustments": {"Breakout-Squeeze": 1.2, "Trend-Pullback": 1.15},
        "order_preference": "stop_entry",
        "exit_posture": "loose_trail",
        "sizing_cap": 1.2,
    },
    "rotation_mean_reversion": {
        "allowed": ["Range-MeanReversion", "Liquidity-Draw/Sweep"],
        "suppressed": ["Breakout-Squeeze"],
        "blocked": [],
        "suppression_multipliers": {"Breakout-Squeeze": 0.65},
        "ranking_adjustments": {"Range-MeanReversion": 1.2, "Liquidity-Draw/Sweep": 1.1},
        "order_preference": "passive_limit",
        "exit_posture": "tight_partials",
        "sizing_cap": 1.0,
    },
    "compression_pre_breakout": {
        "allowed": ["Breakout-Squeeze"],
        "suppressed": ["Range-MeanReversion"],
        "blocked": [],
        "suppression_multipliers": {"Range-MeanReversion": 0.7},
        "ranking_adjustments": {"Breakout-Squeeze": 1.1},
        "order_preference": "stop_entry",
        "exit_posture": "balanced",
        "sizing_cap": 0.9,
    },
    "sweep_reversal": {
        "allowed": ["Liquidity-Draw/Sweep", "Range-MeanReversion"],
        "suppressed": ["Breakout-Squeeze"],
        "blocked": [],
        "suppression_multipliers": {"Breakout-Squeeze": 0.6},
        "ranking_adjustments": {"Liquidity-Draw/Sweep": 1.2},
        "order_preference": "aggressive_limit",
        "exit_posture": "tight_validation",
        "sizing_cap": 0.85,
    },
    "event_chaos": {
        "allowed": ["Breakout-Squeeze"],
        "suppressed": ["Range-MeanReversion", "Liquidity-Draw/Sweep"],
        "blocked": ["Range-MeanReversion"],
        "suppression_multipliers": {"Breakout-Squeeze": 0.75, "Liquidity-Draw/Sweep": 0.5},
        "ranking_adjustments": {"Breakout-Squeeze": 0.8},
        "order_preference": "defensive",
        "exit_posture": "fast_risk_off",
        "sizing_cap": 0.5,
    },
    "dead_zone": {
        "allowed": [],
        "suppressed": ["Breakout-Squeeze", "Range-MeanReversion", "Liquidity-Draw/Sweep"],
        "blocked": ["Breakout-Squeeze", "Trend-Pullback"],
        "suppression_multipliers": {"Breakout-Squeeze": 0.3, "Range-MeanReversion": 0.6, "Liquidity-Draw/Sweep": 0.5},
        "ranking_adjustments": {},
        "order_preference": "none",
        "exit_posture": "flat_bias",
        "sizing_cap": 0.3,
    },
    "uncertain_mixed": {
        "allowed": ["Range-MeanReversion"],
        "suppressed": ["Breakout-Squeeze", "Liquidity-Draw/Sweep"],
        "blocked": [],
        "suppression_multipliers": {"Breakout-Squeeze": 0.8, "Liquidity-Draw/Sweep": 0.85},
        "ranking_adjustments": {},
        "order_preference": "passive_limit",
        "exit_posture": "conservative",
        "sizing_cap": 0.7,
    },
}
