from __future__ import annotations

REGIME_POLICIES: dict[str, dict] = {
    "trend_expansion": {
        "allowed": ["Squeeze-Breakout", "Trend-Pullback"],
        "suppressed": ["Range-MeanReversion"],
        "blocked": [],
        "weight_multipliers": {"Squeeze-Breakout": 1.25, "Trend-Pullback": 1.15, "Range-MeanReversion": 0.6},
        "order_preference": "stop_entry",
        "exit_posture": "loose_trailing",
        "sizing_cap": 1.15,
    },
    "rotation_mean_reversion": {
        "allowed": ["Range-MeanReversion", "Liquidity-Draw/Sweep"],
        "suppressed": ["Squeeze-Breakout", "Trend-Pullback"],
        "blocked": [],
        "weight_multipliers": {"Range-MeanReversion": 1.2, "Liquidity-Draw/Sweep": 1.1, "Squeeze-Breakout": 0.55},
        "order_preference": "passive_limit",
        "exit_posture": "tight_partial_take",
        "sizing_cap": 0.9,
    },
    "compression_pre_breakout": {
        "allowed": ["Squeeze-Breakout", "Trend-Pullback"],
        "suppressed": ["Range-MeanReversion"],
        "blocked": [],
        "weight_multipliers": {"Squeeze-Breakout": 1.05, "Range-MeanReversion": 0.8},
        "order_preference": "aggressive_limit",
        "exit_posture": "watch_escape",
        "sizing_cap": 0.85,
    },
    "sweep_reversal": {
        "allowed": ["Liquidity-Draw/Sweep", "Range-MeanReversion"],
        "suppressed": ["Squeeze-Breakout"],
        "blocked": [],
        "weight_multipliers": {"Liquidity-Draw/Sweep": 1.2, "Range-MeanReversion": 1.05, "Squeeze-Breakout": 0.7},
        "order_preference": "aggressive_limit",
        "exit_posture": "tight_validation",
        "sizing_cap": 0.8,
    },
    "event_chaos": {
        "allowed": ["Squeeze-Breakout"],
        "suppressed": ["Trend-Pullback", "Liquidity-Draw/Sweep"],
        "blocked": ["Range-MeanReversion"],
        "weight_multipliers": {"Squeeze-Breakout": 0.7, "Range-MeanReversion": 0.2},
        "order_preference": "defensive_stop",
        "exit_posture": "fast_fail",
        "sizing_cap": 0.45,
    },
    "dead_zone": {
        "allowed": ["Range-MeanReversion"],
        "suppressed": ["Squeeze-Breakout", "Trend-Pullback", "Liquidity-Draw/Sweep"],
        "blocked": [],
        "weight_multipliers": {"Range-MeanReversion": 0.8, "Squeeze-Breakout": 0.3},
        "order_preference": "passive_limit",
        "exit_posture": "quick_timeout",
        "sizing_cap": 0.4,
    },
    "uncertain_mixed": {
        "allowed": ["Squeeze-Breakout", "Range-MeanReversion", "Liquidity-Draw/Sweep", "Trend-Pullback"],
        "suppressed": [],
        "blocked": [],
        "weight_multipliers": {},
        "order_preference": "balanced",
        "exit_posture": "balanced",
        "sizing_cap": 0.7,
    },
}
